### ISSUE TITLE
PR for asserting on Promise-returning functions?

### ISSUE THREAD

**Issue by Randomage** [janhesters/riteway-jest#1]
Hi,

Would you accept a PR to add support for asserting on functions that return promises?

https://github.com/Randomage/riteway-jest/commit/dda8d5bcc0b716ccc0a6fe15e84cdb131f760541

Thanks

**Comment by janhesters** [comment]
@Randomage You can test asynchronous cade using the `async` keyword.

```js
describe('asyncSum()', async () => {
  // later
  await result = // ...
```
