### ISSUE TITLE
'node_modules/riteway-jest/index.d.ts' is not a module

### ISSUE THREAD

**Issue by angusryer** [janhesters/riteway-jest#7]
Hi @janhesters & @GollyJer -- thanks for working on this project!

I'm using Typescript and RN via Expo. The assert function isn't recognized as a valid test when running `npm test`. My linter shows:
```File <myPath>/node_modules/riteway-jest/index.d.ts' is not a module.``` when hovering over the following line:

```
// gameLogic.spec.ts
import assert from 'riteway-jest';
```

Am I just importing this incorrectly?

**Comment by GollyJer** [comment]
Hi @angusryer.

There's no need to import assert in the test file. Try removing the import and see if that works.

**Comment by angusryer** [comment]
Thanks @GollyJer -- that was one simple fix.
